services:
  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: root1
      POSTGRES_DB: demodb1
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres1 -d demodb1"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # DB_USER: postgres
      # DB_PASSWORD: root
      # DB_HOST: db # zamiast localhost
      # DB_PORT: 5432 # port wewnetrzny bazy
      # DB_NAME: demodb
      DB_USER: postgres1
      DB_PASSWORD: root1
      DB_HOST: db # zamiast localhost
      DB_PORT: 5432 # port wewnetrzny bazy
      DB_NAME: demodb1
    volumes:
      - ./data_csv:/app/data_csv
      - ./database:/app/database

volumes:
  db_data:
